methods: {
  adventureDuration: [Function: bound _createTxObject],
  '0x1e9ca15e': [Function: bound _createTxObject],
  'adventureDuration()': [Function: bound _createTxObject],
  blockedTime: [Function: bound _createTxObject],
  '0x312f8b19': [Function: bound _createTxObject],
  'blockedTime(uint256)': [Function: bound _createTxObject],
  env: [Function: bound _createTxObject],
  '0x9dca0032': [Function: bound _createTxObject],
  'env()': [Function: bound _createTxObject],
  fragmentAmount: [Function: bound _createTxObject],
  '0xc641c4cf': [Function: bound _createTxObject],
  'fragmentAmount()': [Function: bound _createTxObject],
  fragmentRate: [Function: bound _createTxObject],
  '0x853c7240': [Function: bound _createTxObject],
  'fragmentRate()': [Function: bound _createTxObject],
  fragmentToken: [Function: bound _createTxObject],
  '0xa8126c66': [Function: bound _createTxObject],
  'fragmentToken()': [Function: bound _createTxObject],
  mines: [Function: bound _createTxObject],
  '0x2a3a06a7': [Function: bound _createTxObject],
  'mines(uint256)': [Function: bound _createTxObject],
  owner: [Function: bound _createTxObject],
  '0x8da5cb5b': [Function: bound _createTxObject],
  'owner()': [Function: bound _createTxObject],
  porianNFT: [Function: bound _createTxObject],
  '0xc7bf75d2': [Function: bound _createTxObject],
  'porianNFT()': [Function: bound _createTxObject],
  porianPower: [Function: bound _createTxObject],
  '0x571119b5': [Function: bound _createTxObject],
  'porianPower()': [Function: bound _createTxObject],
  renounceOwnership: [Function: bound _createTxObject],
  '0x715018a6': [Function: bound _createTxObject],
  'renounceOwnership()': [Function: bound _createTxObject],
  rentalCentre: [Function: bound _createTxObject],
  '0x25c77ad6': [Function: bound _createTxObject],
  'rentalCentre()': [Function: bound _createTxObject],
  rentalFee: [Function: bound _createTxObject],
  '0x4876956b': [Function: bound _createTxObject],
  'rentalFee()': [Function: bound _createTxObject],
  rentalPriceOf: [Function: bound _createTxObject],
  '0xbf0a660b': [Function: bound _createTxObject],
  'rentalPriceOf(uint256)': [Function: bound _createTxObject],
  reservePool: [Function: bound _createTxObject],
  '0x0266f044': [Function: bound _createTxObject],
  'reservePool()': [Function: bound _createTxObject],
  rewardLevels: [Function: bound _createTxObject],
  '0x992b6099': [Function: bound _createTxObject],
  'rewardLevels(uint256)': [Function: bound _createTxObject],
  rigyReward: [Function: bound _createTxObject],
  '0x047e6513': [Function: bound _createTxObject],
  'rigyReward()': [Function: bound _createTxObject],
  rigyToken: [Function: bound _createTxObject],
  '0xf69c7241': [Function: bound _createTxObject],
  'rigyToken()': [Function: bound _createTxObject],
  rikenReward: [Function: bound _createTxObject],
  '0xeb91c895': [Function: bound _createTxObject],
  'rikenReward()': [Function: bound _createTxObject],
  rikenToken: [Function: bound _createTxObject],
  '0x8584b423': [Function: bound _createTxObject],
  'rikenToken()': [Function: bound _createTxObject],
  transferOwnership: [Function: bound _createTxObject],
  '0xf2fde38b': [Function: bound _createTxObject],
  'transferOwnership(address)': [Function: bound _createTxObject],
  turnDuration: [Function: bound _createTxObject],
  '0x05066917': [Function: bound _createTxObject],
  'turnDuration()': [Function: bound _createTxObject],
  winRatio: [Function: bound _createTxObject],
  '0x82bb8a7d': [Function: bound _createTxObject],
  'winRatio()': [Function: bound _createTxObject],
  initialize: [Function: bound _createTxObject],
  '0xc4d66de8': [Function: bound _createTxObject],
  'initialize(address)': [Function: bound _createTxObject],
  setGameDuration: [Function: bound _createTxObject],
  '0x54b6239b': [Function: bound _createTxObject],
  'setGameDuration(uint256,uint256)': [Function: bound _createTxObject],
  setGameEnv: [Function: bound _createTxObject],
  '0x8f709230': [Function: bound _createTxObject],
  'setGameEnv(uint8)': [Function: bound _createTxObject],
  setRewardLevels: [Function: bound _createTxObject],
  '0xc125ffd2': [Function: bound _createTxObject],
  'setRewardLevels(uint256[4],uint256[4])': [Function: bound _createTxObject],
  setRewardConfigs: [Function: bound _createTxObject],
  '0x213fd494': [Function: bound _createTxObject],
  'setRewardConfigs(address,address,uint256,uint256,uint256)': [Function: bound _createTxObject],
  setPorianContractAddress: [Function: bound _createTxObject],
  '0x8c592903': [Function: bound _createTxObject],
  'setPorianContractAddress(address,address,address)': [Function: bound _createTxObject],
  setFragmentConfigs: [Function: bound _createTxObject],
  '0xafc99853': [Function: bound _createTxObject],
  'setFragmentConfigs(uint256,uint256,address)': [Function: bound _createTxObject],
  onAuthorized: [Function: bound _createTxObject],
  '0x5a199e45': [Function: bound _createTxObject],
  'onAuthorized(address,address,uint256,uint256,bytes12,bytes)': [Function: bound _createTxObject],
  withdrawPorians: [Function: bound _createTxObject],
  '0x3444663a': [Function: bound _createTxObject],
  'withdrawPorians(uint256[])': [Function: bound _createTxObject],
  getOwnerOf: [Function: bound _createTxObject],
  '0x99321e12': [Function: bound _createTxObject],
  'getOwnerOf(uint256,uint256)': [Function: bound _createTxObject],
  startAdventure: [Function: bound _createTxObject],
  '0x30057802': [Function: bound _createTxObject],
  'startAdventure(uint256[3],uint8[3],bool)': [Function: bound _createTxObject],
  support1: [Function: bound _createTxObject],
  '0xf163a51c': [Function: bound _createTxObject],
  'support1(uint256,uint256[3],uint8[3],bool)': [Function: bound _createTxObject],
  fortify: [Function: bound _createTxObject],
  '0xf9977794': [Function: bound _createTxObject],
  'fortify(uint256,uint256,uint8)': [Function: bound _createTxObject],
  support2: [Function: bound _createTxObject],
  '0xa1745737': [Function: bound _createTxObject],
  'support2(uint256,uint256,uint8)': [Function: bound _createTxObject],
  finish: [Function: bound _createTxObject],
  '0xd353a1cb': [Function: bound _createTxObject],
  'finish(uint256)': [Function: bound _createTxObject],
  _calculateNormalReward: [Function: bound _createTxObject],
  '0x8f30ec1c': [Function: bound _createTxObject],
  '_calculateNormalReward(bytes32,bytes12)': [Function: bound _createTxObject],
  _calculateBigReward: [Function: bound _createTxObject],
  '0x450fe7c9': [Function: bound _createTxObject],
  '_calculateBigReward(uint256,uint256,uint256,uint256,uint8)': [Function: bound _createTxObject],
  atkPowerOf: [Function: bound _createTxObject],
  '0x4a0fb891': [Function: bound _createTxObject],
  'atkPowerOf(uint256,uint8)': [Function: bound _createTxObject],
  defPowerOf: [Function: bound _createTxObject],
  '0x717ea8e5': [Function: bound _createTxObject],
  'defPowerOf(uint256,uint8)': [Function: bound _createTxObject],
  randomRewardLevel: [Function: bound _createTxObject],
  '0xa1c6b957': [Function: bound _createTxObject],
  'randomRewardLevel(bytes32)': [Function: bound _createTxObject],
  setRewardMap: [Function: bound _createTxObject],
  '0x190cac33': [Function: bound _createTxObject],
  'setRewardMap(bytes32,uint8,uint8,uint8)': [Function: bound _createTxObject],
  getRewardInfo: [Function: bound _createTxObject],
  '0xba3d0b3b': [Function: bound _createTxObject],
  'getRewardInfo(bytes32,uint8)': [Function: bound _createTxObject],
  setEnv2RewardMap: [Function: bound _createTxObject],
  '0x4708d883': [Function: bound _createTxObject],
  'setEnv2RewardMap(bytes32,uint8)': [Function: bound _createTxObject],
  getEnvOf: [Function: bound _createTxObject],
  '0x99ec4ce0': [Function: bound _createTxObject],
  'getEnvOf(bytes32)': [Function: bound _createTxObject],
  setStartTime2RewardMap: [Function: bound _createTxObject],
  '0xcb788f78': [Function: bound _createTxObject],
  'setStartTime2RewardMap(bytes32,uint64)': [Function: bound _createTxObject],
  getStartTimeOfRewardMap: [Function: bound _createTxObject],
  '0x0d7f8b69': [Function: bound _createTxObject],
  'getStartTimeOfRewardMap(bytes32)': [Function: bound _createTxObject],
  getRewardOf: [Function: bound _createTxObject],
  '0x57282550': [Function: bound _createTxObject],
  'getRewardOf(uint256,uint256)': [Function: bound _createTxObject]
},
events: {
  AdventureFinished: [Function: bound ],
  '0xacba132576685783d626ee7ff7486ac6cf8580b51ca1ef49ee36edb6303ac735': [Function: bound ],
  'AdventureFinished(uint256,address,uint256,uint256,uint256,uint256,uint256)': [Function: bound ],
  AdventureFortified: [Function: bound ],
  '0x71b4d764a280d810a1907567eb53bcf7ebe267f0d94d40d2a5f20009e7b73569': [Function: bound ],
  'AdventureFortified(uint256,uint256,uint8,uint8,uint256)': [Function: bound ],
  AdventureStarted: [Function: bound ],
  '0xd498194e39f0d0d9426ee530bd16b2182b34d07d968365c8fdcaf73c5a6d0ac5': [Function: bound ],
  'AdventureStarted(uint256,address,uint256,uint256[3],uint8[3],uint8[3],uint256)': [Function: bound ],
  AdventureSupported1: [Function: bound ],
  '0xbe2e74f68284a904ef29e10f3e20b2c9bb540481fb9903c1aead3e26cc56f8b1': [Function: bound ],
  'AdventureSupported1(uint256,address,uint256[3],uint8[3],uint8[3],uint256)': [Function: bound ],
  AdventureSupported2: [Function: bound ],
  '0x6dbf0858232497280bfdf35e37adf2002793779d07d4f48947b17509c71dd41c': [Function: bound ],
  'AdventureSupported2(uint256,uint256,uint8,uint8,uint256)': [Function: bound ],
  FragmentConfigsChanged: [Function: bound ],
  '0xe239076e097097397bd9d5b0e6c2cf73fa948431155a5a0f93fff9a5ef931f30': [Function: bound ],
  'FragmentConfigsChanged(uint256,uint256,address)': [Function: bound ],
  GameDurationChanged: [Function: bound ],
  '0xc62be04bfb76e5e364578771d33bb80ebbea7219b67ba068fb4bbdaf83e4a3c0': [Function: bound ],
  'GameDurationChanged(uint256,uint256)': [Function: bound ],
  GameEnvChanged: [Function: bound ],
  '0x43a1267f2f5c7e858648d6d699524ead9bcf11432ca3560bc07d8b0ad4bd9716': [Function: bound ],
  'GameEnvChanged(uint8)': [Function: bound ],
  NoFragments: [Function: bound ],
  '0x53c10eaba1434d4e73bbb8836944fead356a79f60bd5c1b18baa66f31c59a44a': [Function: bound ],
  'NoFragments()': [Function: bound ],
  OwnershipTransferred: [Function: bound ],
  '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0': [Function: bound ],
  'OwnershipTransferred(address,address)': [Function: bound ],
  PorianContractAddressChanged: [Function: bound ],
  '0x8de8db18cfc6fdcc2ca3eb256388082c038e90fb2cd81537a8f421787f42ba47': [Function: bound ],
  'PorianContractAddressChanged(address,address,address)': [Function: bound ],
  PorianDeposited: [Function: bound ],
  '0xc42131d410ea79f1eafecd549df9a392681974b7f4d9f4d78c216ea12b6766e8': [Function: bound ],
  'PorianDeposited(address,uint256,uint256)': [Function: bound ],
  PorianWithdrawed: [Function: bound ],
  '0x44402a61584354899786311a4f0c7bf924b31db70b5ebef891d88cee08156ed5': [Function: bound ],
  'PorianWithdrawed(address,uint256)': [Function: bound ],
  RentalConfigsSet: [Function: bound ],
  '0xa55ac5460860c980f8995911e6122b7c03cf8018de722e71ff691901f0f337eb': [Function: bound ],
  'RentalConfigsSet(uint256,address)': [Function: bound ],
  RewardConfigsChanged: [Function: bound ],
  '0xb60316123b8b94ddfa73b438b8ad0809fbac14d9a92e091e56626864940f0099': [Function: bound ],
  'RewardConfigsChanged(address,address,uint256,uint256,uint256)': [Function: bound ],
  RewardLevelChanged: [Function: bound ],
  '0x9317361a686b977b3b5ffa913a5fbf59f72e48479ea70cd0ebe40437aa8458d7': [Function: bound ],
  'RewardLevelChanged(uint256,uint256,uint256)': [Function: bound ],
  allEvents: [Function: bound ]
},
_address: '0x70d66d12c424Db41bf4E501A3FBbF5D4a779E66b',
_jsonInterface: [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
    constant: undefined,
    payable: undefined
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'AdventureFinished',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xacba132576685783d626ee7ff7486ac6cf8580b51ca1ef49ee36edb6303ac735'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'AdventureFortified',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x71b4d764a280d810a1907567eb53bcf7ebe267f0d94d40d2a5f20009e7b73569'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'AdventureStarted',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xd498194e39f0d0d9426ee530bd16b2182b34d07d968365c8fdcaf73c5a6d0ac5'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'AdventureSupported1',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xbe2e74f68284a904ef29e10f3e20b2c9bb540481fb9903c1aead3e26cc56f8b1'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'AdventureSupported2',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x6dbf0858232497280bfdf35e37adf2002793779d07d4f48947b17509c71dd41c'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'FragmentConfigsChanged',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xe239076e097097397bd9d5b0e6c2cf73fa948431155a5a0f93fff9a5ef931f30'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'GameDurationChanged',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xc62be04bfb76e5e364578771d33bb80ebbea7219b67ba068fb4bbdaf83e4a3c0'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'GameEnvChanged',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x43a1267f2f5c7e858648d6d699524ead9bcf11432ca3560bc07d8b0ad4bd9716'
  },
  {
    anonymous: false,
    inputs: [],
    name: 'NoFragments',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x53c10eaba1434d4e73bbb8836944fead356a79f60bd5c1b18baa66f31c59a44a'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'OwnershipTransferred',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'PorianContractAddressChanged',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x8de8db18cfc6fdcc2ca3eb256388082c038e90fb2cd81537a8f421787f42ba47'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'PorianDeposited',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xc42131d410ea79f1eafecd549df9a392681974b7f4d9f4d78c216ea12b6766e8'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'PorianWithdrawed',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x44402a61584354899786311a4f0c7bf924b31db70b5ebef891d88cee08156ed5'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'RentalConfigsSet',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xa55ac5460860c980f8995911e6122b7c03cf8018de722e71ff691901f0f337eb'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'RewardConfigsChanged',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0xb60316123b8b94ddfa73b438b8ad0809fbac14d9a92e091e56626864940f0099'
  },
  {
    anonymous: false,
    inputs: [Array],
    name: 'RewardLevelChanged',
    type: 'event',
    constant: undefined,
    payable: undefined,
    signature: '0x9317361a686b977b3b5ffa913a5fbf59f72e48479ea70cd0ebe40437aa8458d7'
  },
  {
    inputs: [],
    name: 'adventureDuration',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x1e9ca15e'
  },
  {
    inputs: [Array],
    name: 'blockedTime',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x312f8b19'
  },
  {
    inputs: [],
    name: 'env',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x9dca0032'
  },
  {
    inputs: [],
    name: 'fragmentAmount',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xc641c4cf'
  },
  {
    inputs: [],
    name: 'fragmentRate',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x853c7240'
  },
  {
    inputs: [],
    name: 'fragmentToken',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xa8126c66'
  },
  {
    inputs: [Array],
    name: 'mines',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x2a3a06a7'
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x8da5cb5b'
  },
  {
    inputs: [],
    name: 'porianNFT',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xc7bf75d2'
  },
  {
    inputs: [],
    name: 'porianPower',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x571119b5'
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x715018a6'
  },
  {
    inputs: [],
    name: 'rentalCentre',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x25c77ad6'
  },
  {
    inputs: [],
    name: 'rentalFee',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x4876956b'
  },
  {
    inputs: [Array],
    name: 'rentalPriceOf',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xbf0a660b'
  },
  {
    inputs: [],
    name: 'reservePool',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x0266f044'
  },
  {
    inputs: [Array],
    name: 'rewardLevels',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x992b6099'
  },
  {
    inputs: [],
    name: 'rigyReward',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x047e6513'
  },
  {
    inputs: [],
    name: 'rigyToken',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xf69c7241'
  },
  {
    inputs: [],
    name: 'rikenReward',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xeb91c895'
  },
  {
    inputs: [],
    name: 'rikenToken',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x8584b423'
  },
  {
    inputs: [Array],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xf2fde38b'
  },
  {
    inputs: [],
    name: 'turnDuration',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x05066917'
  },
  {
    inputs: [],
    name: 'winRatio',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x82bb8a7d'
  },
  {
    inputs: [Array],
    name: 'initialize',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xc4d66de8'
  },
  {
    inputs: [Array],
    name: 'setGameDuration',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x54b6239b'
  },
  {
    inputs: [Array],
    name: 'setGameEnv',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x8f709230'
  },
  {
    inputs: [Array],
    name: 'setRewardLevels',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xc125ffd2'
  },
  {
    inputs: [Array],
    name: 'setRewardConfigs',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x213fd494'
  },
  {
    inputs: [Array],
    name: 'setPorianContractAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x8c592903'
  },
  {
    inputs: [Array],
    name: 'setFragmentConfigs',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xafc99853'
  },
  {
    inputs: [Array],
    name: 'onAuthorized',
    outputs: [Array],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x5a199e45'
  },
  {
    inputs: [Array],
    name: 'withdrawPorians',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x3444663a'
  },
  {
    inputs: [Array],
    name: 'getOwnerOf',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x99321e12'
  },
  {
    inputs: [Array],
    name: 'startAdventure',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0x30057802'
  },
  {
    inputs: [Array],
    name: 'support1',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xf163a51c'
  },
  {
    inputs: [Array],
    name: 'fortify',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xf9977794'
  },
  {
    inputs: [Array],
    name: 'support2',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xa1745737'
  },
  {
    inputs: [Array],
    name: 'finish',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
    constant: undefined,
    payable: undefined,
    signature: '0xd353a1cb'
  },
  {
    inputs: [Array],
    name: '_calculateNormalReward',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x8f30ec1c'
  },
  {
    inputs: [Array],
    name: '_calculateBigReward',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x450fe7c9'
  },
  {
    inputs: [Array],
    name: 'atkPowerOf',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x4a0fb891'
  },
  {
    inputs: [Array],
    name: 'defPowerOf',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x717ea8e5'
  },
  {
    inputs: [Array],
    name: 'randomRewardLevel',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xa1c6b957'
  },
  {
    inputs: [Array],
    name: 'setRewardMap',
    outputs: [Array],
    stateMutability: 'pure',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x190cac33'
  },
  {
    inputs: [Array],
    name: 'getRewardInfo',
    outputs: [Array],
    stateMutability: 'pure',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xba3d0b3b'
  },
  {
    inputs: [Array],
    name: 'setEnv2RewardMap',
    outputs: [Array],
    stateMutability: 'pure',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x4708d883'
  },
  {
    inputs: [Array],
    name: 'getEnvOf',
    outputs: [Array],
    stateMutability: 'pure',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x99ec4ce0'
  },
  {
    inputs: [Array],
    name: 'setStartTime2RewardMap',
    outputs: [Array],
    stateMutability: 'pure',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0xcb788f78'
  },
  {
    inputs: [Array],
    name: 'getStartTimeOfRewardMap',
    outputs: [Array],
    stateMutability: 'pure',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x0d7f8b69'
  },
  {
    inputs: [Array],
    name: 'getRewardOf',
    outputs: [Array],
    stateMutability: 'view',
    type: 'function',
    constant: true,
    payable: undefined,
    signature: '0x57282550'
  }
]